import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.scss";
import Footer from "@/components/footer";
import { Toaster } from "react-hot-toast";
import Redirecionamento from "@/components/redirecionamento";
import WsIcon from "@/components/wsicon";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Produtos Grupo Du",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={`${poppins.variable}`}>
        <Toaster position="top-center" reverseOrder={false} gutter={8} />
        <Redirecionamento />
        <WsIcon />
        {children}
        <Footer />
      </body>
    </html>
  );
}
